Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut07.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut08.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut09.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut10.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut11.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut12.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut01.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut02.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut03.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut04.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\cgcut01.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\cgcut02.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\cgcut03.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng01.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng02.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng03.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng04.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng05.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng06.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng07.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp1.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp2.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp3.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp4.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp5.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp6.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp7.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp8.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp9.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp10.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp11.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp12.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp13.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp14.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp15.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp16.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp17.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp18.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp19.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp20.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp21.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp22.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp23.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp24.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp25.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_1.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_2.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_3.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_1.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_2.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_3.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_1.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_2.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_3.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_1.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_2.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_3.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_1.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_2.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_3.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_1.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_2.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_3.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_1.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_2.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_3.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl1.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl2.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl3.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl4.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl5.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl6.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl7.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl8.txt
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl9.txt