Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_t7a.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_t7b.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_t7c.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_t7d.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_t7e.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n1a.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n1b.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n1c.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n1d.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n1e.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n2a.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n2b.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n2c.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n2d.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n2e.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n3a.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n3b.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n3c.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n3d.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n3e.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n4a.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n4b.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n4c.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n4d.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n4e.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n5a.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n5b.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n5c.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n5d.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n5e.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n6a.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n6b.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n6c.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n6d.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n6e.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n7a.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n7b.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n7c.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n7d.txt	2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht_n7e.txt	2	4	5	3
