
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl9.txt					2	4	5	3
