Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng02.txt					8	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng03.txt					8	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng04.txt					8	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng05.txt					8	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng06.txt					8	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng07.txt					8	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng08.txt					8	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng09.txt					8	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng10.txt					8	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng02.txt 8 4 5 3
