Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut01.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut02.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut03.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut04.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut05.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut06.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut07.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut08.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut09.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut10.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut11.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut12.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut01.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut02.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut03.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut04.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut05.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut06.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut07.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut08.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut09.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut10.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut11.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut12.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut13.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\cgcut01.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\cgcut02.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\cgcut03.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng01.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng02.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng03.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng04.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng05.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng06.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng07.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng08.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng09.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng10.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp1.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp2.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp3.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp4.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp5.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp6.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp7.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp8.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp9.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp10.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp11.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp12.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp13.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp14.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp15.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp16.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp17.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp18.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp19.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp20.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp21.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp22.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp23.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp24.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp25.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_1.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_2.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_3.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_1.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_2.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_3.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_1.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_2.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_3.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_1.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_2.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_3.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_1.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_2.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_3.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_1.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_2.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_3.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_1.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_2.txt					8	4	5	4
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_3.txt					8	4	5	4
