Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_1_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_2_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_3_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_4_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_5_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_6_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_7_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_8_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_9_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_26.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_27.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_28.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_29.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_30.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_31.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_32.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_33.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_34.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_35.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_36.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_37.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_38.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_39.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_40.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_41.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_42.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_43.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_44.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_45.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_46.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_47.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_48.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_49.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\Class_10_50.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut01.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut02.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut03.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut04.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut05.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut06.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut07.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut08.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut09.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ngcut12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut01.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut02.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut03.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut04.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut05.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut06.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut07.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\gcut08.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\cgcut01.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\cgcut02.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\cgcut03.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng01.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng02.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng03.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng04.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng05.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng06.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\beng07.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp9.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp10.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp11.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp12.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp13.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp14.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp15.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp16.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp17.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp18.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp19.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp20.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp21.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp22.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp23.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp24.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scp25.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht1_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht2_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht3_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht4_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht5_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht6_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\ht7_3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl1.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl2.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl3.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl4.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl5.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl6.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl7.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl8.txt					2	4	5	3
Release\Cutting C:\afrank\ProblemaCorteStrip\Instancias\scpl9.txt					2	4	5	3
